name = input("Enter name: ")
age = input("Enter age: ")
house_num = input("Enter House number:")
street_name = input("Enter Street name: ")
print(f"This is {name} he is {age} years old and lives at house number:{house_num} on {street_name} Street")