pro1 = input("Enter 1st product name: ")
price1 = float(input("Enter 1st product's price: "))
pro2 = input("Enter 2nd product name: ")
price2 = float(input("Enter 2nd product's price: "))
pro3 = input("Enter 3rd product name: ")
price3 = float(input("Enter 3rd product's price: "))
total = round(price1 + price2 + price3, 2)
average = round(total / 3, 2)
print(f"The total of [{pro1}], [{pro2}], [{pro3}] is {total} and the average price of the items is {average}")